bazelbuild/tulsi

- src/Tulsi/ConfigEditorBuildTargetSelectorViewController.swift
I didn't find in history if there was a reason why `ios_static_framework` was not included in list of supported target by Tulsi, but after adding it project for framework is generated and works just fine.
> Added `ios_static_framework` to list of supported targets

- src/TulsiGenerator/DeploymentTarget.swift
This fixes building a Watch app with Xcode 12 beta occuring the
following error:
```
Unknown active compilation target of "watchos_x86_64". Please report a Tulsi bug.
```
> Add x86_64 to the list of supported watchOS CPUs

- src/TulsiGenerator/TulsiProject.swift
- src/TulsiGeneratorTests/TulsiProjectTests.swift
I experienced that, when using the option `--create-tulsiproj`, the list of packages in the generated `project.tulsiconf` file was changing its ordering every time, which is a problem if `project.tulsiconf` is under source control
> Sort bazel packages when saving, so the generated tulsiconf file does not change every time it is generated

- src/TulsiGenerator/PBXTargetGenerator.swift
- src/TulsiGenerator/TulsiOptionSet.swift
- src/TulsiGenerator/XcodeProjectGenerator.swift
- src/TulsiGenerator/en.lproj/Options.strings
- src/TulsiGeneratorTests/PBXTargetGeneratorTests.swift
- src/TulsiGeneratorTests/XcodeProjectGeneratorTests.swift
Previously the filters did not apply to test targets, meaning any direct deps of
test bundles would be included in the project unconditionally.
PiperOrigin-RevId: 327238250
> Apply source filters to test sources

- README.md
- build_and_run.sh
I just checked out Tulsi and noticed it didn't build out of the box.
The error I got was:
```
BUILD:30:13: in xcode_config rule @local_config_xcode//:host_xcodes: --xcode_version=11.5
specified, but '11.5' is not an available Xcode version.
available versions: [11.7.0.11E801a, 11.6.0.11N700h, 12.0.0.12A8189n].
If you believe you have '11.5' installed, try running "bazel shutdown", and then
re-run your command.
```
Xcode 11.7 is the latest stable version shipped by Apple.
> Update build_and_run script to use Xcode 11.7

- src/TulsiGenerator/Bazel/tulsi/tulsi_aspects.bzl
This fixes 'Did not find a dSYM bundle...' warnings in the Xcode build
output when we're not building with dSYMs.
> Fix issue that makes Tulsi thinks that dSYMs are being generated when they aren't

- src/TulsiGenerator/DeploymentTarget.swift
Resolves #206 
I'm new to Tulsi and am unsure if there is a test suite covering `validCPUs`, but do point them out if I'm just missing them!
> Add arm64 (Apple Silicon) to valid CPUs for macOS

- .bazelrc
Without this the tests don't pass locally. This was already added for CI
> Add HOME to test_env

- src/TulsiGenerator/en.lproj/Localizable.strings
Remove action required and give an example of a case where the current behavior is intentional.
PiperOrigin-RevId: 350153865
(cherry picked from commit 3c1506a800c86bdefb363f2bb62b6613b2a4196e)
> Update multi min OS version warning message

- src/TulsiGenerator/Bazel/tulsi/tulsi_aspects.bzl
This is phase 2 of of the switch to toolchain transitions. See https://github.com/bazelbuild/bazel/issues/11584 for details.
PiperOrigin-RevId: 338462410
(cherry picked from commit 06d3ebf9c5277b5117edaf3ec81ace3811726956)
> Update Bazel CC-using rules to use the toolchain transition.

- src/TulsiGenerator/Bazel/tulsi/tulsi_aspects.bzl
`SwiftInfo` allows module maps to be passed as `File` or `string` (the latter to support paths of system modules in Xcode SDKs), so filter out any elements that aren't `File`s.
PiperOrigin-RevId: 357989635
(cherry picked from commit 0e4a897ad83bb18ff52c790d4cf619c4c585a7a6)
> Only collect module maps that are files.

- src/TulsiGenerator/BazelLocator.swift
We're currently using the `--create-tulsiproj` flag to generate our Tulsi project, and it seems like it's caching the bazel executable it finds. This is problematic when for example upgrading bazelisk or bazel via brew, since the cached path will be invalid, resulting in an error like this:
```
[Error] Bazel could not be found at "file:///usr/local/bin/bazel". Please update the path in the project file.
```
The quickest fix is to check if the path exists, and if it doesn't, then we re-run the `BazelLocator` logic to find the new executable.
> [TulsiGenerator] Don't use cached Bazel if it doesn't exist anymore

- src/TulsiGenerator/Bazel/tulsi/tulsi_aspects.bzl
- src/TulsiGenerator/PBXTargetGenerator.swift
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SimpleCCProject.xcodeproj/project.pbxproj
When a file belongs in an external repository, it should be looked up via
`$(TULSI_BWRS)` at all times, even if generated.
Fix detecting wether a file is external or not by looking its owner's
`workspace_root`, instead of the path prefix.
While at it, make use of `File.is_directory` if it's available.
Fixes https://github.com/bazelbuild/tulsi/issues/164.
> Properly generate paths for external files and include directories

- src/TulsiGenerator/Scripts/bazel_build.py
This reverts commit 07cd4a0ee534efb18c49760bf406b795dd432ea5.
As of Xcode 12, this is no longer an issue. Xcode now displays pcm not
found warnings correctly as warnings.
> Revert "Fix Tulsi generated project showing .pcm not found warnings as errors (#136)"

- src/TulsiGenerator/XcodeProjectGenerator.swift
PiperOrigin-RevId: 361938153
(cherry picked from commit 77d8ebe411acb2414f5236799517e4d4a39e42b9)
> Make generating an xcode project to a path with whitespace an error when using project level lldbinit.

- src/TulsiGenerator/Scripts/bootstrap_lldbinit.py
The source_idx var which tracks which line in the tulsi block we are looking for was being incremented past the length of the tulsi block resulting in an out of range error. Once source_idx exceeds the length of the tulsi block, it no longer makes sense to check whether the line in the lldbinit file matches a line in the tulsi block so this change adds a gaurd for that condition.
PiperOrigin-RevId: 363674993
(cherry picked from commit 16d7b338e2dffb2e53a766e08bcfd0ca0a8135b8)
> Fix an issue where the lldbinit parsing logic throws an out of range error when the lldbinit contained content after the tulsi block.

- src/TulsiGenerator/BazelPBXReferencePatcher.swift
The tulsi workspace is in `<project>.xcodeproj/.tulsi/tulsi-workspace/`
and not in the `tulsi-workspace/`. To get the xcodeproj path, put the
source group relative the SourceRoot, which is the .xcodeproj's parent
directory.
I'm not sure about this approach though, but at least it works for us.
Fixes #109.
> Resolve external source files inside the tulsi workspace

- src/TulsiGenerator/BuildLabel.swift
External BuildLabels were keeping their // halfway through their path, leading to projects xcode would refuse to load.
As an example: @google_toolbox_for_mac//Foundation:BUILD was going to external//Foundation/BUILD, not external/Foundation/BUILD.
This lead the pbjproj to assign the file the path //Foundation/BUILD, which Xcode refuses to load, along with groups named '/' and the omission of other associated source files.
[Noticed while writing #255, separated for ease of review.]
> Fix broken external BuildLabel filename parsing

- src/TulsiGenerator/Scripts/bazel_build.py
Xcode 13 adds new frameworks which are injected into the test runner.
These must be resigned as well otherwise the app will fail to install
due to a certificate expired/revoked error.
PiperOrigin-RevId: 417654389
(cherry picked from commit 7ff52cd4f8482bac6db148be1c5dea3408a7dd80)
> Fix signing of test runners with Xcode 13

- src/TulsiGenerator/TulsiOptionSet.swift
- src/TulsiGenerator/XcodeProjectGenerator.swift
- src/TulsiGenerator/en.lproj/Options.strings
The new build system isn't officially supported yet, so I've added
this flag in preparation for support although it's `true` (legacy)
by default.
This should supplement #277 although I haven't thoroughly tested the new build system support (especially on device + for tests) yet.
PiperOrigin-RevId: 417654737
(cherry picked from commit 2cbc9236818025b471689bd8a1810e6c0655a18a)
Closes https://github.com/bazelbuild/tulsi/pull/277
> Add UseLegacyBuildSystem option to swap between new/old build systems

- src/TulsiGenerator/BazelAspectInfoExtractor.swift
Fixes https://github.com/bazelbuild/tulsi/issues/296.
Note that building Tulsi itself still requires Bazel 5.0+.
> Use `--noexperimental_run_validations` instead of `--norun_validations` to make Tulsi works with projects that are still using Bazel 4.

- WORKSPACE
This validates folks who are building tulsi don't hit surprising errors.
We should bump this over time
> Add minimum bazel version check

- src/Tulsi/HeadlessXcodeProjectGenerator.swift
- src/Tulsi/TulsiCommandlineParser.swift
- src/TulsiEndToEndTests/BUILD
- src/TulsiEndToEndTests/BuildFlags.swift
- src/TulsiEndToEndTests/TulsiEndToEndTest.swift
- src/TulsiGenerator/TulsiOption.swift
We'll use + test this ourselves during the E2E generation tests.
PiperOrigin-RevId: 424868778
(cherry picked from commit c305374b0a9be7fcdf3f0f146ef8dc1b12546cc0)
> Add the ability to specify extra build flags via the CLI during project generation

- .bazelci/presubmit.yml
- .github/workflows/macos.yml
- README.md
- build_and_run.sh
- src/TulsiGeneratorIntegrationTests/BazelIntegrationTestCase.swift
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/AppClipProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/ComplexSingleProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/MacOSProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/MacOSTestsProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/MultiExtensionProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SimpleCCProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SimpleProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SkylarkBundlingProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SwiftProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/TestSuiteExplicitXCTestsProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/TestSuiteLocalTaggedTestsProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/TestSuiteRecursiveTestSuiteProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/WatchProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/update_goldens.sh
Need to bump rules_apple + Bazel requirement since we require a flag new in Bazel 5
for our tests.
PiperOrigin-RevId: 425968191
(cherry picked from commit 81d85ec1ca222bef40601193909e19812020a30c)
> Update to build with Xcode 13.2.1

- src/TulsiGenerator/PBXTargetGenerator.swift
Only warnings left now are hashValue, which are a bit more complicated
to fix due to our usage in PBXObjectProtocol.
PiperOrigin-RevId: 426146113
(cherry picked from commit 0ea4f83afa7f378294c642e9c7994d5ce33335e0)
> Fix minor warning in TulsiGenerator

- src/TulsiGenerator/Scripts/bazel_build.py
Since Tulsi appends this flag to the build command,
`--output_groups=tulsi_outputs,default` would override any previously
defined `--output_groups` flag.
From the
[documentation](https://bazel.build/reference/command-line-reference#flag--output_groups):
`--output_groups=+foo,+bar` builds the union of the `default` set,
`foo`, and `bar`, while `--output_groups=foo,bar` overrides the default
set such that only `foo` and `bar` are built.
> Do not override user-defined output groups

- src/TulsiGenerator/Bazel/tulsi/tulsi_aspects.bzl
Resolves #285 
I believe recent Xcodes may have relied on this file to give Xcode information about where the source lives while indexing. 
This does not appear to fix syntax highlighting for cross-module types, but jump-to does seem to work well.
> Add swiftsourceinfo/swiftdoc to list of copied includes

- WORKSPACE
To work around the drop of `should_lipo` in
`apple_common.link_multi_arch_binary`.
> Use an unreleased revision of rules_apple for now

- src/TulsiGenerator/PBXObjects.swift
- src/TulsiGenerator/PBXTargetGenerator.swift
- src/TulsiGenerator/Scripts/bazel_build.py
- src/TulsiGenerator/Scripts/clang_stub.sh
- src/TulsiGenerator/Scripts/ld_stub.sh
- src/TulsiGenerator/Scripts/swiftc_stub.py
- src/TulsiGenerator/TulsiXcodeProjectGenerator.swift
- src/TulsiGenerator/XcodeProjectGenerator.swift
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/AppClipProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/ComplexSingleProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/MacOSProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/MacOSTestsProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/MultiExtensionProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SimpleCCProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SimpleProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SkylarkBundlingProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SwiftProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/TestSuiteExplicitXCTestsProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/TestSuiteLocalTaggedTestsProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/TestSuiteRecursiveTestSuiteProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/WatchProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorTests/PBXTargetGeneratorTests.swift
- src/TulsiGeneratorTests/XcodeProjectGeneratorTests.swift
Currently this will only be used if the `UseLegacyBuildSystem` option
is false.
PiperOrigin-RevId: 428076981
(cherry picked from commit 0fb177476c76043167546a9a7b3aae692738e1b0)
> Add support for stub binaries

- .bazelrc
Workaround to make it builds with Xcode 13.3.
Fixes https://github.com/bazelbuild/tulsi/issues/323
> Always build Tulsi with WMO for now

- src/TulsiGeneratorIntegrationTests/BUILD
The current timeout is not long enough to run on GitHub Actions.
> Change size of AspectTests

- src/Tulsi/ConfigEditorBuildTargetSelectorViewController.swift
There is missing "ios_dynamic_framework" target that Bazel supports.
> Added "ios_dynamic_framework" in filteredFileTypes

- src/TulsiGenerator/Bazel/tulsi/tulsi_aspects.bzl
add function to collect XCFramework on bazel aspect, to support [native xcframework rules](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-apple.md#apple_dynamic_xcframework_import)
|Before|After|
|----|----|
|<img width="268" alt="Screen Shot 2022-04-21 at 15 28 10" src="https://user-images.githubusercontent.com/16457495/164413470-65d9f123-5d33-45bd-a20b-b87c52b9bcc8.png">|<img width="372" alt="Screen Shot 2022-04-21 at 15 19 42" src="https://user-images.githubusercontent.com/16457495/164413375-7f07f4a2-7a53-4f6a-96e6-0130f01a4cf1.png">|
> Support XCFramework

- .bazelrc
- src/TulsiEndToEndTests/Resources/Buttons.tulsiproj/Configs/Buttons.tulsigen
- src/TulsiGeneratorIntegrationTests/BazelIntegrationTestCase.swift
Now that the swift worker uses json instead of protobuf this is no
longer a concern
> Remove RULES_SWIFT_BUILD_DUMMY_WORKER

- .github/workflows/build.yml
There's a change in Bazel rolling that is required for this:
https://github.com/bazelbuild/bazel/blob/4858cbfa37d5ed96fb282280819a3577064eb51d/src/main/java/com/google/devtools/build/lib/rules/config/ConfigGlobalLibrary.java#L123-L126
Otherwise the build would fail with:
```
Error in transition: Invalid transition input
'//command_line_option:incompatible_enable_apple_toolchain_resolution'.
Cannot transition on --experimental_* or --incompatible_* options
```
> Use rolling release for `macos_latest_head_deps`

- src/TulsiGenerator/PBXObjects.swift
- src/TulsiGenerator/PBXProjSerializer.swift
- src/TulsiGenerator/PBXTargetGenerator.swift
- src/TulsiGenerator/Scripts/bazel_build.py
- src/TulsiGenerator/Scripts/resigner.py
- src/TulsiGenerator/TulsiXcodeProjectGenerator.swift
- src/TulsiGenerator/XcodeProjectGenerator.swift
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/ComplexSingleProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/ComplexSingleProject.xcodeproj/xcshareddata/xcschemes/_idx_Scheme.xcscheme
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SimpleProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorTests/PBXTargetGeneratorTests.swift
- src/TulsiGeneratorTests/XcodeProjectGeneratorTests.swift
Since the new build system will always inject the test artifacts
after our run script phase for UI tests, we instead add a new
PBXAggregateTarget which allows us to run another script after
the initial UI test target (including the runner) is built.
In addition, we no longer attach xcdatamodels to indexer targets
since it can trigger issues in the new build system. Xcode
has issues inferring their paths and can accidentally scan
the workspace root instead of the xcdatamodeld dir.
PiperOrigin-RevId: 428078393
(cherry picked from commit 65607ed821c4d540cc9f75563e2f06392bebc8e3)
> Add support for resigning UI tests with the new build system

- src/TulsiGenerator/Bazel/tulsi/tulsi_aspects.bzl
This ensures framework search paths are collected properly for indexing
targets.
> Collect framework paths from xcframework imports

- src/TulsiGeneratorIntegrationTests/BUILD
This is required after the following change:
https://github.com/bazelbuild/rules_swift/commit/d39d9660d125c9b0f2d455726db15df162c4d8e2
> Add `testonly = True` to `swift_library` targets in tests

- README.md
To achieve better hermetic build, users can integrate Tulsi into their project as an external dependency. Add document
about how to do this in README.
The rendered result can be seen [here](https://github.com/kkpattern/tulsi/tree/doc_hermetic_install#integrating-into-your-project).
Any feedback would be appreciated.
Closes #353
> Add document for integrating Tulsi into project

- BUILD
- src/Tulsi/AnnouncementBanner.swift
- src/Tulsi/Base.lproj/SplashScreenWindowController.xib
- src/Tulsi/BazelSelectionPanel.swift
- src/Tulsi/SplashScreenWindowController.swift
- src/TulsiGeneratorTests/BUILD
- src/tools/bazel_cache_reader/BUILD
- src/tools/module_cache_pruner/BUILD
- src/tools/module_cache_pruner/tests/BUILD
1. Not overlap the other controls on the splash screen
2. Accept clicks on the entire banner, not just the label
3. Have more muted colors that work both in light and dark mode
Also bumped the target macOS version to 11.0
PiperOrigin-RevId: 438868252
(cherry picked from commit 2ae8dd5968567c5ef69f3a90022e6ba1145bc64a)
> Modified the announcement banner to:

- src/Tulsi/HeadlessTulsiProjectCreator.swift
- src/Tulsi/HeadlessXcodeProjectGenerator.swift
- src/Tulsi/TulsiCommandlineParser.swift
PiperOrigin-RevId: 445422722
(cherry picked from commit 4b8a5444a426bd687edfc10f121837065489ae3f)
> Made --mark-read work as an argument to other modes

- src/TulsiEndToEndTests/Resources/Buttons/BUILD
- src/TulsiGeneratorIntegrationTests/AspectTests.swift
- src/TulsiGeneratorIntegrationTests/Resources/Watch.BUILD
"deps" implies code dependencies, which the existing watchos_application rule does not support. However, single target watchOS applications which will be supported by a watchos_single_target_application rule and eventually the watchos_application rule itself do own code dependencies. That changes the meaning of "deps" as it is used today.
The "deps" attr will be removed from the watchos_application in a future change on rules_apple, which will be tracked in [].
PiperOrigin-RevId: 474890643
(cherry picked from commit 6b532f6e877bdae7ec30f0c68940eb5f4f3590a6)
> Migrate away from "deps" to "storyboards" and "resources".

- src/TulsiGeneratorIntegrationTests/Resources/ComplexSingle.BUILD
Apple framework import rules processing will now enforce framework
bundles include a binary file with the same name as the framework bundle.
This change adds a dummy framework binary file to the `ObjCFramework`
test target to conform to this (future) enforcement.
PiperOrigin-RevId: 452401907
(cherry picked from commit c454b1dc22d4c8f99326026491342a991abb8a91)
> Add dummy framework binary to ObjCFramework test target

- src/TulsiEndToEndTests/Resources/Buttons/BUILD
PiperOrigin-RevId: 449304144
(cherry picked from commit 3ffd508789877221a145c6028aa1f146b57cac9f)
> Upload `load` statements in Tulsi to use the build-definition-specific files instead of the umbrella `swift.bzl`.

- src/TulsiGenerator/PBXObjects.swift
- src/TulsiGenerator/PBXTargetGenerator.swift
- src/TulsiGenerator/Scripts/resigner.py
- src/TulsiGenerator/XcodeProjectGenerator.swift
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/AppClipProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/ComplexSingleProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/MacOSProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/MacOSTestsProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/MultiExtensionProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SimpleCCProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SimpleProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SkylarkBundlingProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/SwiftProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/TestSuiteExplicitXCTestsProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/TestSuiteLocalTaggedTestsProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/TestSuiteRecursiveTestSuiteProject.xcodeproj/project.pbxproj
- src/TulsiGeneratorIntegrationTests/Resources/GoldenProjects/WatchProject.xcodeproj/project.pbxproj
- Add resigner targets to test_suite targets' schemes so the test
suites schemes work properly
- Mark our build script as always needing to run (always out of date)
since we always need to run bazel to make sure it's up to date.
- Don't disable signing for iOS simulator since we still need Xcode
to codesign the test runner + injected dylibs.
- Resign the new XCTestSupport.framework
PiperOrigin-RevId: 457805542
(cherry picked from commit b28485834eafe807c3a3bac0484801b20e98c7ac)
> Various fixes for the new build system (+ Xcode 14)

- src/TulsiGenerator/Bazel/tulsi/tulsi_aspects.bzl
We would like to migrate all such usage to CppConfiguration so that we
can delete the info in ObjcConfiguration.
PiperOrigin-RevId: 457484452
(cherry picked from commit c57119b4bc6c1ce34cc4f331fb359c973276f940)
> Migrate ObjcConfiguration usage to equivalent info in CppConfiguration

- src/TulsiGenerator/Scripts/bazel_build.py
*** Reason for rollback ***
Breaks builds for physical device targets running OS versions that do not directly map to floats, e.g. on my phone running iOS 15.6.1:
ValueError: could not convert string to float: '15.6.1'
*** Original change description ***
Update the Info.plist mtime of any embedded bundles after copying the Bazel build artifacts over to DerivedData. This matches Xcode behavior and more importantly prevents an issue on iOS 16 or newer devices where incrmeental installations fail due to delta bundles not having a bundle ID because they don't have an Info.plist.
PiperOrigin-RevId: 478566431
(cherry picked from commit b748e0ab3cad1fb681de44a0a028bfccb0681940)
> Automated rollback of commit fc3edc67433192d4742d80de49a6ffbb58e76d63.

- .gitignore
Otherwise running `src/TulsiGeneratorIntegrationTests/update_goldens.sh`
would add them to git.
> Ignore generated Tulsi configs in golden projects from version control

- src/TulsiEndToEndTests/BUILD
- src/TulsiGenerator/ProcessRunner.swift
- src/TulsiGeneratorIntegrationTests/BUILD
- src/TulsiGeneratorIntegrationTests/BazelFakeWorkspace.swift
- src/TulsiGeneratorIntegrationTests/BazelIntegrationTestCase.swift
This is so that Tulsi doesn't have to maintain a fork of the Python build rule
infrastructure files
PiperOrigin-RevId: 466952546
(cherry picked from commit e52359d47270101c60476111123ab4fa923a5c31)
Conflicts:
src/TulsiEndToEndTests/BUILD
src/TulsiGeneratorIntegrationTests/BUILD
> Make Tulsi integration tests re-use Python integration test setup scripts.
